version: '3.8'

services:
  glpi:
    image: "glpi/glpi:${GLPI_VERSION:-latest}"
    container_name: glpi-web
    environment:
      # DB connection (required)
      GLPI_DB_HOST: ${DB_HOST:?DB_HOST is required}
      GLPI_DB_NAME: ${DB_NAME:?DB_NAME is required}
      GLPI_DB_USER: ${DB_USER:?DB_USER is required}
      GLPI_DB_PORT: ${DB_PORT:-3306}
      GLPI_DB_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD is required}
      TZ: ${TZ:-Asia/Taipei}
    ports:
      - 8081:80
    volumes:
      - glpi-storage:/var/glpi:rw
    depends_on:
      - glpi-db
    networks:
      - shared-network
    restart: always

  glpi-db:
    image: "mariadb:${DB_VER:-latest}"
    container_name: ${DB_HOST:?DB_HOST is required}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:?DB_ROOT_PASSWORD is required}
      MARIADB_DATABASE: ${DB_NAME:?DB_NAME is required}
      MARIADB_USER: ${DB_USER:?DB_USER is required}
      MARIADB_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD is required}
    volumes:
      - glpi-db-data:/var/lib/mysql
    networks:
      - shared-network
    restart: always

  # One-shot service to remove install/ after GLPI installation completes
  glpi-postinstall:
    image: busybox:1.36
    depends_on:
      - glpi
    volumes:
      - glpi-storage:/var/www/glpi:rw
    entrypoint: /bin/sh -c
    command: |
      i=0
      echo "glpi-postinstall: waiting for config/config_db.php"
      while [ $i -lt 90 ]; do
        if [ -f /var/www/glpi/config/config_db.php ]; then
          echo "config found, removing install files"
          # optional backup: tar -czf /var/www/glpi/install-backup-$(date +%s).tgz /var/www/glpi/install || true
          rm -f /var/www/glpi/install/install.php || true
          rm -rf /var/www/glpi/install || true
          echo "install removed"
          exit 0
        fi
        i=$((i+1))
        sleep 2
      done
      echo "glpi-postinstall: timeout waiting for config, exiting"; exit 0
    restart: 'no'

volumes:
  glpi-db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${GLPI_DB_DATA_DIR}

  glpi-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${GLPI_STORAGE_DIR}

networks:
  shared-network:
    external: true
    name: shared-network
